export const ResponseCode = Object.freeze({
    SUCCESS: 200,
    INTERNAL_SERVER_ERROR: 500,
    UNAUTHORIZED: 401,
    UNPROCESSABLE_CONTENT: 422,
    CREATED: 201,
    INVALID_CREDENTIALS: 601,
    EMAIL_EXITS: 602,
    VALIDATION_ERROR: 400,
});
